catalogMode: prefer

cleanupUnusedCatalogs: true

publicHoistPattern:
  - "*@rbxts*"
shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  build:
    roblox-ts: ^3.0.0
    typescript: 5.5.3
  dev:
    "@rbxts/jest": 3.13.3-ts.1
    "@rbxts/jest-globals": 3.13.3-ts.1
  lint:
    "@isentinel/eslint-config": ^4.7.6
    eslint: ^9.39.2
    eslint-plugin-pnpm: ^1.5.0
  script:
    jiti: ^2.6.1
  types:
    "@rbxts/compiler-types": 3.0.0-types.0
    "@rbxts/types": ^1.0.903

onlyBuiltDependencies:
  - unrs-resolver
