name: Publish

on:
  push:
    tags: [v*, workflow_dispatch]

permissions:
  contents: read

  id-token: write # Required for OIDC
jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          cache: pnpm

          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install

      - name: Print versions
        run: |
          git --version
          node --version
          pnpm --version

      - name: Build
        run: |
          pnpm rbxtsc --type package --verbose

      - name: Publish
        run: | # Remove the --dry-run when ready to really publish
          pnpm publish --dry-run
